const modal=document.querySelector('#modal'),host=document.querySelector('#gameHost');document.querySelector('.close').onclick=()=>modal.classList.remove('open');modal.onclick=e=>{if(e.target===modal)modal.classList.remove('open')};
document.querySelectorAll('.game-card').forEach(c=>c.querySelector('button').onclick=()=>{modal.classList.add('open');openGame(c.dataset.game)});
function shell(title,html){host.innerHTML=`<div class="play-area"><h2>${title}</h2>${html}</div>`}
function openGame(g){({snake,ttt,chess,runner,cycle,archery,mind}[g])()}

function snake(){shell('🐍 SNAKE',`<div class="score">Score: <b id="sc">0</b> — Arrow keys / WASD</div><canvas id="c" width="400" height="400"></canvas>`);let c=document.querySelector('#c'),x=c.getContext('2d'),s=20,p=[{x:200,y:200}],d={x:s,y:0},f={x:300,y:200},score=0;addEventListener('keydown',e=>{let k=e.key.toLowerCase();if(k==='arrowup'||k==='w')if(d.y===0)d={x:0,y:-s};if(k==='arrowdown'||k==='s')if(d.y===0)d={x:0,y:s};if(k==='arrowleft'||k==='a')if(d.x===0)d={x:-s,y:0};if(k==='arrowright'||k==='d')if(d.x===0)d={x:s,y:0}});function loop(){let h={x:p[0].x+d.x,y:p[0].y+d.y};if(h.x<0||h.y<0||h.x>=400||h.y>=400||p.some(a=>a.x===h.x&&a.y===h.y)){p=[{x:200,y:200}];d={x:s,y:0};score=0}else{p.unshift(h);if(h.x===f.x&&h.y===f.y){score++;document.querySelector('#sc').textContent=score;f={x:Math.floor(Math.random()*20)*s,y:Math.floor(Math.random()*20)*s}}else p.pop()}x.clearRect(0,0,400,400);x.fillStyle='#00f6ff';x.fillRect(f.x,f.y,s-2,s-2);x.fillStyle='#ff2bd6';p.forEach(a=>x.fillRect(a.x,a.y,s-2,s-2))}setInterval(loop,100)}

function ttt(){shell('❌⭕ TIC TAC TOE',`<div class="score" id="msg">Your turn</div><div class="tttgrid" id="ttt"></div><button onclick="ttt()">RESET</button>`);let b=Array(9).fill(''),grid=document.querySelector('#ttt'),m=document.querySelector('#msg');b.forEach((_,i)=>{let q=document.createElement('button');q.onclick=()=>{if(b[i])return;b[i]='X';q.textContent='X';if(win('X'))return m.textContent='You win!';if(b.every(Boolean))return m.textContent='Draw';let a=b.map((v,j)=>v?'':j).filter(v=>v!=='');let j=a[Math.floor(Math.random()*a.length)];b[j]='O';grid.children[j].textContent='O';if(win('O'))m.textContent='Computer wins!'};grid.appendChild(q)});function win(z){return [[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]].some(r=>r.every(i=>b[i]===z))}}

function chess(){let pieces=['♜','♞','♝','♛','♚','♝','♞','♜','♟','♟','♟','♟','♟','♟','♟','♟','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','♙','♙','♙','♙','♙','♙','♙','♙','♖','♘','♗','♕','♔','♗','♘','♖'];shell('♞ CHESS BOARD',`<p>Practice board — click any square to move a piece visually.</p><div class="chess" id="board"></div>`);let bd=document.querySelector('#board');pieces.forEach((p,i)=>{let q=document.createElement('div');q.className=(Math.floor(i/8)+i)%2?'dark':'light';q.textContent=p;q.onclick=()=>{if(q.textContent){let first=[...bd.children].find(z=>z.dataset.sel);if(first){first.textContent=q.textContent;q.textContent='';delete first.dataset.sel}else q.dataset.sel=1}};bd.appendChild(q)})}

function runner(){shell('🏃 SPEED RUNNER',`<div class="score">SPACE = jump • Score: <b id="rs">0</b></div><canvas id="r" width="650" height="260"></canvas>`);let c=document.querySelector('#r'),x=c.getContext('2d'),y=205,vy=0,obs=[],score=0,over=false;onkeydown=e=>{if(e.code==='Space'&&y>=205)vy=-13;if(e.code==='Space'&&over)location.reload()};function f(){x.clearRect(0,0,650,260);x.fillStyle='#15152a';x.fillRect(0,220,650,4);vy+=.7;y+=vy;if(y>205)y=205;if(Math.random()<.025)obs.push({x:650,w:22});obs.forEach(o=>o.x-=6);obs=obs.filter(o=>o.x>-30);if(obs.some(o=>o.x<80&&o.x+o.w>45&&y>180)){over=true;x.fillStyle='#ff2bd6';x.font='28px Orbitron';x.fillText('GAME OVER — SPACE TO RESTART',90,100)}if(!over)score++,document.querySelector('#rs').textContent=Math.floor(score/10);x.fillStyle='#00f6ff';x.fillRect(45,y,30,15);x.fillStyle='#ff2bd6';obs.forEach(o=>x.fillRect(o.x,190,22,30));requestAnimationFrame(f)}f()}

function cycle(){shell('🚲 CYCLE RUSH',`<div class="score">LEFT / RIGHT to dodge • Score: <b id="cs">0</b></div><canvas id="cy" width="600" height="320"></canvas>`);let c=document.querySelector('#cy'),x=c.getContext('2d'),px=280,obs=[],sc=0;onkeydown=e=>{if(e.key==='ArrowLeft')px-=25;if(e.key==='ArrowRight')px+=25;px=Math.max(80,Math.min(500,px))};function f(){x.fillStyle='#090914';x.fillRect(0,0,600,320);x.fillStyle='#24243c';x.fillRect(70,0,460,320);x.strokeStyle='#777';x.setLineDash([20,20]);x.lineDashOffset=-sc;x.beginPath();x.moveTo(300,0);x.lineTo(300,320);x.stroke();x.setLineDash([]);if(Math.random()<.035)obs.push({x:90+Math.random()*400,y:-30});obs.forEach(o=>o.y+=5);obs=obs.filter(o=>o.y<350);x.fillStyle='#00f6ff';x.fillRect(px,260,35,40);x.fillStyle='#ff2bd6';obs.forEach(o=>x.fillRect(o.x,o.y,35,35));if(obs.some(o=>Math.abs(o.x-px)<30&&o.y>230)){sc=0;obs=[]}sc++;document.querySelector('#cs').textContent=Math.floor(sc/10);requestAnimationFrame(f)}f()}

function archery(){shell('🏹 NEON ARCHERY',`<div class="score">Click the target • Score: <b id="as">0</b></div><canvas id="a" width="600" height="360"></canvas>`);let c=document.querySelector('#a'),x=c.getContext('2d'),score=0,tx=450,ty=180;x.fillStyle='#05050c';function draw(){x.clearRect(0,0,600,360);x.strokeStyle='#444';x.beginPath();x.moveTo(0,330);x.lineTo(600,330);x.stroke();x.fillStyle='#ff2bd6';x.beginPath();x.arc(tx,ty,48,0,7);x.fill();x.fillStyle='#0a0a12';x.beginPath();x.arc(tx,ty,28,0,7);x.fill();x.fillStyle='#00f6ff';x.beginPath();x.arc(tx,ty,10,0,7);x.fill()}c.onclick=e=>{let r=c.getBoundingClientRect(),mx=(e.clientX-r.left)*600/r.width,my=(e.clientY-r.top)*360/r.height,d=Math.hypot(mx-tx,my-ty);if(d<48)score+=d<10?10:d<28?5:2;else score=Math.max(0,score-1);document.querySelector('#as').textContent=score;tx=390+Math.random()*170;ty=60+Math.random()*230;draw()};draw()}

function mind(){let icons=['🚀','🎮','👾','⚡','🧠','🔥','🎯','🏆'],arr=[...icons,...icons].sort(()=>Math.random()-.5);shell('🧠 MIND MATRIX',`<div class="score">Match all pairs • Moves: <b id="mm">0</b></div><div class="memory" id="mem"></div>`);let box=document.querySelector('#mem'),first=null,lock=false,moves=0;arr.forEach(v=>{let b=document.createElement('button');b.textContent=v;b.onclick=()=>{if(lock||b.classList.contains('show'))return;b.classList.add('show');if(!first)first=b;else{moves++;document.querySelector('#mm').textContent=moves;if(first.textContent===b.textContent){first=null}else{lock=true;setTimeout(()=>{first.classList.remove('show');b.classList.remove('show');first=null;lock=false},500)}}};box.appendChild(b)})}
